/*
 * This file is generated by jOOQ.
 */
package storysflower.com.storysflower.model.tables.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import storysflower.com.storysflower.model.tables.tables.ImageProduct;


/**
 * image product table
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageProductRecord extends TableRecordImpl<ImageProductRecord> implements Record3<Long, Long, Boolean> {

    private static final long serialVersionUID = 1588483247;

    /**
     * Setter for <code>public.image_product.product_id</code>.
     */
    public void setProductId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.image_product.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.image_product.image_id</code>.
     */
    public void setImageId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.image_product.image_id</code>.
     */
    public Long getImageId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.image_product.main_image</code>.
     */
    public void setMainImage(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.image_product.main_image</code>.
     */
    public Boolean getMainImage() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ImageProduct.IMAGE_PRODUCT.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ImageProduct.IMAGE_PRODUCT.IMAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return ImageProduct.IMAGE_PRODUCT.MAIN_IMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getImageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getMainImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getImageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getMainImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageProductRecord value1(Long value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageProductRecord value2(Long value) {
        setImageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageProductRecord value3(Boolean value) {
        setMainImage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageProductRecord values(Long value1, Long value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageProductRecord
     */
    public ImageProductRecord() {
        super(ImageProduct.IMAGE_PRODUCT);
    }

    /**
     * Create a detached, initialised ImageProductRecord
     */
    public ImageProductRecord(Long productId, Long imageId, Boolean mainImage) {
        super(ImageProduct.IMAGE_PRODUCT);

        set(0, productId);
        set(1, imageId);
        set(2, mainImage);
    }
}
