/*
 * This file is generated by jOOQ.
 */
package storysflower.com.storysflower.model.tables;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.buy_product_id_seq</code>
     */
    public static final Sequence<Long> BUY_PRODUCT_ID_SEQ = new SequenceImpl<Long>("buy_product_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.cart_id_seq</code>
     */
    public static final Sequence<Long> CART_ID_SEQ = new SequenceImpl<Long>("cart_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.category_id_seq</code>
     */
    public static final Sequence<Long> CATEGORY_ID_SEQ = new SequenceImpl<Long>("category_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.customer_id_seq</code>
     */
    public static final Sequence<Long> CUSTOMER_ID_SEQ = new SequenceImpl<Long>("customer_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.deal_product_id_seq</code>
     */
    public static final Sequence<Long> DEAL_PRODUCT_ID_SEQ = new SequenceImpl<Long>("deal_product_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.favourite_id_seq</code>
     */
    public static final Sequence<Long> FAVOURITE_ID_SEQ = new SequenceImpl<Long>("favourite_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.image_image_id_seq</code>
     */
    public static final Sequence<Long> IMAGE_IMAGE_ID_SEQ = new SequenceImpl<Long>("image_image_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.occasion_occasion_id_seq</code>
     */
    public static final Sequence<Long> OCCASION_OCCASION_ID_SEQ = new SequenceImpl<Long>("occasion_occasion_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.product_id_seq</code>
     */
    public static final Sequence<Long> PRODUCT_ID_SEQ = new SequenceImpl<Long>("product_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.rating_id_seq</code>
     */
    public static final Sequence<Long> RATING_ID_SEQ = new SequenceImpl<Long>("rating_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.recipient_id_seq</code>
     */
    public static final Sequence<Long> RECIPIENT_ID_SEQ = new SequenceImpl<Long>("recipient_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.review_id_seq</code>
     */
    public static final Sequence<Long> REVIEW_ID_SEQ = new SequenceImpl<Long>("review_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.topic_topic_id_seq</code>
     */
    public static final Sequence<Long> TOPIC_TOPIC_ID_SEQ = new SequenceImpl<Long>("topic_topic_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_id_seq</code>
     */
    public static final Sequence<Long> USER_ID_SEQ = new SequenceImpl<Long>("user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.user_role_id_seq</code>
     */
    public static final Sequence<Long> USER_ROLE_ID_SEQ = new SequenceImpl<Long>("user_role_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
