/*
 * This file is generated by jOOQ.
 */
package storysflower.com.storysflower.model.tables;


import javax.annotation.Generated;

import storysflower.com.storysflower.model.tables.tables.BuyProduct;
import storysflower.com.storysflower.model.tables.tables.Cart;
import storysflower.com.storysflower.model.tables.tables.Category;
import storysflower.com.storysflower.model.tables.tables.Customer;
import storysflower.com.storysflower.model.tables.tables.DealProduct;
import storysflower.com.storysflower.model.tables.tables.Favourite;
import storysflower.com.storysflower.model.tables.tables.Image;
import storysflower.com.storysflower.model.tables.tables.ImageProduct;
import storysflower.com.storysflower.model.tables.tables.Occasion;
import storysflower.com.storysflower.model.tables.tables.Product;
import storysflower.com.storysflower.model.tables.tables.ProductCategory;
import storysflower.com.storysflower.model.tables.tables.Rating;
import storysflower.com.storysflower.model.tables.tables.Recipient;
import storysflower.com.storysflower.model.tables.tables.Review;
import storysflower.com.storysflower.model.tables.tables.Topic;
import storysflower.com.storysflower.model.tables.tables.User;
import storysflower.com.storysflower.model.tables.tables.UserRole;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * buy product table
     */
    public static final BuyProduct BUY_PRODUCT = storysflower.com.storysflower.model.tables.tables.BuyProduct.BUY_PRODUCT;

    /**
     * cart table
     */
    public static final Cart CART = storysflower.com.storysflower.model.tables.tables.Cart.CART;

    /**
     * category table
     */
    public static final Category CATEGORY = storysflower.com.storysflower.model.tables.tables.Category.CATEGORY;

    /**
     * customer table
     */
    public static final Customer CUSTOMER = storysflower.com.storysflower.model.tables.tables.Customer.CUSTOMER;

    /**
     * deal product table
     */
    public static final DealProduct DEAL_PRODUCT = storysflower.com.storysflower.model.tables.tables.DealProduct.DEAL_PRODUCT;

    /**
     * favourite table
     */
    public static final Favourite FAVOURITE = storysflower.com.storysflower.model.tables.tables.Favourite.FAVOURITE;

    /**
     * image table
     */
    public static final Image IMAGE = storysflower.com.storysflower.model.tables.tables.Image.IMAGE;

    /**
     * image product table
     */
    public static final ImageProduct IMAGE_PRODUCT = storysflower.com.storysflower.model.tables.tables.ImageProduct.IMAGE_PRODUCT;

    /**
     * occasion table
     */
    public static final Occasion OCCASION = storysflower.com.storysflower.model.tables.tables.Occasion.OCCASION;

    /**
     * product table
     */
    public static final Product PRODUCT = storysflower.com.storysflower.model.tables.tables.Product.PRODUCT;

    /**
     * product category table
     */
    public static final ProductCategory PRODUCT_CATEGORY = storysflower.com.storysflower.model.tables.tables.ProductCategory.PRODUCT_CATEGORY;

    /**
     * rating table
     */
    public static final Rating RATING = storysflower.com.storysflower.model.tables.tables.Rating.RATING;

    /**
     * recipient table
     */
    public static final Recipient RECIPIENT = storysflower.com.storysflower.model.tables.tables.Recipient.RECIPIENT;

    /**
     * review table
     */
    public static final Review REVIEW = storysflower.com.storysflower.model.tables.tables.Review.REVIEW;

    /**
     * topic table
     */
    public static final Topic TOPIC = storysflower.com.storysflower.model.tables.tables.Topic.TOPIC;

    /**
     * user table
     */
    public static final User USER = storysflower.com.storysflower.model.tables.tables.User.USER;

    /**
     * user role table
     */
    public static final UserRole USER_ROLE = storysflower.com.storysflower.model.tables.tables.UserRole.USER_ROLE;
}
