/*
 * This file is generated by jOOQ.
 */
package storysflower.com.storysflower.model.tables;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import storysflower.com.storysflower.model.tables.tables.BuyProduct;
import storysflower.com.storysflower.model.tables.tables.Cart;
import storysflower.com.storysflower.model.tables.tables.Category;
import storysflower.com.storysflower.model.tables.tables.Customer;
import storysflower.com.storysflower.model.tables.tables.DealProduct;
import storysflower.com.storysflower.model.tables.tables.Favourite;
import storysflower.com.storysflower.model.tables.tables.Image;
import storysflower.com.storysflower.model.tables.tables.Occasion;
import storysflower.com.storysflower.model.tables.tables.Product;
import storysflower.com.storysflower.model.tables.tables.Rating;
import storysflower.com.storysflower.model.tables.tables.Recipient;
import storysflower.com.storysflower.model.tables.tables.Review;
import storysflower.com.storysflower.model.tables.tables.Topic;
import storysflower.com.storysflower.model.tables.tables.User;
import storysflower.com.storysflower.model.tables.tables.UserRole;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BUY_PRODUCT_PKEY = Indexes0.BUY_PRODUCT_PKEY;
    public static final Index CART_PKEY = Indexes0.CART_PKEY;
    public static final Index CATEGORY_CATEGORY_NAME_KEY = Indexes0.CATEGORY_CATEGORY_NAME_KEY;
    public static final Index CATEGORY_PKEY = Indexes0.CATEGORY_PKEY;
    public static final Index CUSTOMER_EMAIL_KEY = Indexes0.CUSTOMER_EMAIL_KEY;
    public static final Index CUSTOMER_PKEY = Indexes0.CUSTOMER_PKEY;
    public static final Index DEAL_PRODUCT_PKEY = Indexes0.DEAL_PRODUCT_PKEY;
    public static final Index FAVOURITE_PKEY = Indexes0.FAVOURITE_PKEY;
    public static final Index IMAGE_PKEY = Indexes0.IMAGE_PKEY;
    public static final Index OCCASION_NAME_OCCASION_KEY = Indexes0.OCCASION_NAME_OCCASION_KEY;
    public static final Index OCCASION_PKEY = Indexes0.OCCASION_PKEY;
    public static final Index PRODUCT_PKEY = Indexes0.PRODUCT_PKEY;
    public static final Index RATING_PKEY = Indexes0.RATING_PKEY;
    public static final Index RECIPIENT_PKEY = Indexes0.RECIPIENT_PKEY;
    public static final Index REVIEW_PKEY = Indexes0.REVIEW_PKEY;
    public static final Index TOPIC_PKEY = Indexes0.TOPIC_PKEY;
    public static final Index TOPIC_TOPIC_NAME_KEY = Indexes0.TOPIC_TOPIC_NAME_KEY;
    public static final Index USER_EMAIL_KEY = Indexes0.USER_EMAIL_KEY;
    public static final Index USER_PKEY = Indexes0.USER_PKEY;
    public static final Index USER_ROLE_PKEY = Indexes0.USER_ROLE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BUY_PRODUCT_PKEY = Internal.createIndex("buy_product_pkey", BuyProduct.BUY_PRODUCT, new OrderField[] { BuyProduct.BUY_PRODUCT.ID }, true);
        public static Index CART_PKEY = Internal.createIndex("cart_pkey", Cart.CART, new OrderField[] { Cart.CART.ID }, true);
        public static Index CATEGORY_CATEGORY_NAME_KEY = Internal.createIndex("category_category_name_key", Category.CATEGORY, new OrderField[] { Category.CATEGORY.CATEGORY_NAME }, true);
        public static Index CATEGORY_PKEY = Internal.createIndex("category_pkey", Category.CATEGORY, new OrderField[] { Category.CATEGORY.ID }, true);
        public static Index CUSTOMER_EMAIL_KEY = Internal.createIndex("customer_email_key", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.EMAIL }, true);
        public static Index CUSTOMER_PKEY = Internal.createIndex("customer_pkey", Customer.CUSTOMER, new OrderField[] { Customer.CUSTOMER.ID }, true);
        public static Index DEAL_PRODUCT_PKEY = Internal.createIndex("deal_product_pkey", DealProduct.DEAL_PRODUCT, new OrderField[] { DealProduct.DEAL_PRODUCT.ID }, true);
        public static Index FAVOURITE_PKEY = Internal.createIndex("favourite_pkey", Favourite.FAVOURITE, new OrderField[] { Favourite.FAVOURITE.ID }, true);
        public static Index IMAGE_PKEY = Internal.createIndex("image_pkey", Image.IMAGE, new OrderField[] { Image.IMAGE.IMAGE_ID }, true);
        public static Index OCCASION_NAME_OCCASION_KEY = Internal.createIndex("occasion_name_occasion_key", Occasion.OCCASION, new OrderField[] { Occasion.OCCASION.NAME_OCCASION }, true);
        public static Index OCCASION_PKEY = Internal.createIndex("occasion_pkey", Occasion.OCCASION, new OrderField[] { Occasion.OCCASION.OCCASION_ID }, true);
        public static Index PRODUCT_PKEY = Internal.createIndex("product_pkey", Product.PRODUCT, new OrderField[] { Product.PRODUCT.ID }, true);
        public static Index RATING_PKEY = Internal.createIndex("rating_pkey", Rating.RATING, new OrderField[] { Rating.RATING.ID }, true);
        public static Index RECIPIENT_PKEY = Internal.createIndex("recipient_pkey", Recipient.RECIPIENT, new OrderField[] { Recipient.RECIPIENT.ID }, true);
        public static Index REVIEW_PKEY = Internal.createIndex("review_pkey", Review.REVIEW, new OrderField[] { Review.REVIEW.ID }, true);
        public static Index TOPIC_PKEY = Internal.createIndex("topic_pkey", Topic.TOPIC, new OrderField[] { Topic.TOPIC.TOPIC_ID }, true);
        public static Index TOPIC_TOPIC_NAME_KEY = Internal.createIndex("topic_topic_name_key", Topic.TOPIC, new OrderField[] { Topic.TOPIC.TOPIC_NAME }, true);
        public static Index USER_EMAIL_KEY = Internal.createIndex("user_email_key", User.USER, new OrderField[] { User.USER.EMAIL }, true);
        public static Index USER_PKEY = Internal.createIndex("user_pkey", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_ROLE_PKEY = Internal.createIndex("user_role_pkey", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ID }, true);
    }
}
