/*
 * This file is generated by jOOQ.
 */
package storysflower.com.storysflower.model.tables.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import storysflower.com.storysflower.model.tables.tables.Recipient;


/**
 * recipient table
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipientRecord extends UpdatableRecordImpl<RecipientRecord> implements Record6<Long, String, String, String, String, String> {

    private static final long serialVersionUID = 1260050796;

    /**
     * Setter for <code>public.recipient.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.recipient.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.recipient.full_name</code>.
     */
    public void setFullName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.recipient.full_name</code>.
     */
    public String getFullName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.recipient.address</code>.
     */
    public void setAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.recipient.address</code>.
     */
    public String getAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.recipient.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.recipient.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.recipient.message_to_recipient</code>.
     */
    public void setMessageToRecipient(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.recipient.message_to_recipient</code>.
     */
    public String getMessageToRecipient() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.recipient.message_to_us</code>.
     */
    public void setMessageToUs(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.recipient.message_to_us</code>.
     */
    public String getMessageToUs() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Recipient.RECIPIENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Recipient.RECIPIENT.FULL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Recipient.RECIPIENT.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Recipient.RECIPIENT.PHONE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Recipient.RECIPIENT.MESSAGE_TO_RECIPIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Recipient.RECIPIENT.MESSAGE_TO_US;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMessageToRecipient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMessageToUs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFullName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMessageToRecipient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMessageToUs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipientRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipientRecord value2(String value) {
        setFullName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipientRecord value3(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipientRecord value4(String value) {
        setPhoneNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipientRecord value5(String value) {
        setMessageToRecipient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipientRecord value6(String value) {
        setMessageToUs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipientRecord values(Long value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecipientRecord
     */
    public RecipientRecord() {
        super(Recipient.RECIPIENT);
    }

    /**
     * Create a detached, initialised RecipientRecord
     */
    public RecipientRecord(Long id, String fullName, String address, String phoneNumber, String messageToRecipient, String messageToUs) {
        super(Recipient.RECIPIENT);

        set(0, id);
        set(1, fullName);
        set(2, address);
        set(3, phoneNumber);
        set(4, messageToRecipient);
        set(5, messageToUs);
    }
}
