/*
 * This file is generated by jOOQ.
 */
package storysflower.com.storysflower.model.tables;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import storysflower.com.storysflower.model.tables.tables.BuyProduct;
import storysflower.com.storysflower.model.tables.tables.Cart;
import storysflower.com.storysflower.model.tables.tables.Category;
import storysflower.com.storysflower.model.tables.tables.Customer;
import storysflower.com.storysflower.model.tables.tables.DealProduct;
import storysflower.com.storysflower.model.tables.tables.Favourite;
import storysflower.com.storysflower.model.tables.tables.Image;
import storysflower.com.storysflower.model.tables.tables.ImageProduct;
import storysflower.com.storysflower.model.tables.tables.Occasion;
import storysflower.com.storysflower.model.tables.tables.Product;
import storysflower.com.storysflower.model.tables.tables.ProductCategory;
import storysflower.com.storysflower.model.tables.tables.Rating;
import storysflower.com.storysflower.model.tables.tables.Recipient;
import storysflower.com.storysflower.model.tables.tables.Review;
import storysflower.com.storysflower.model.tables.tables.Topic;
import storysflower.com.storysflower.model.tables.tables.User;
import storysflower.com.storysflower.model.tables.tables.UserRole;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1075189717;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * buy product table
     */
    public final BuyProduct BUY_PRODUCT = storysflower.com.storysflower.model.tables.tables.BuyProduct.BUY_PRODUCT;

    /**
     * cart table
     */
    public final Cart CART = storysflower.com.storysflower.model.tables.tables.Cart.CART;

    /**
     * category table
     */
    public final Category CATEGORY = storysflower.com.storysflower.model.tables.tables.Category.CATEGORY;

    /**
     * customer table
     */
    public final Customer CUSTOMER = storysflower.com.storysflower.model.tables.tables.Customer.CUSTOMER;

    /**
     * deal product table
     */
    public final DealProduct DEAL_PRODUCT = storysflower.com.storysflower.model.tables.tables.DealProduct.DEAL_PRODUCT;

    /**
     * favourite table
     */
    public final Favourite FAVOURITE = storysflower.com.storysflower.model.tables.tables.Favourite.FAVOURITE;

    /**
     * image table
     */
    public final Image IMAGE = storysflower.com.storysflower.model.tables.tables.Image.IMAGE;

    /**
     * image product table
     */
    public final ImageProduct IMAGE_PRODUCT = storysflower.com.storysflower.model.tables.tables.ImageProduct.IMAGE_PRODUCT;

    /**
     * occasion table
     */
    public final Occasion OCCASION = storysflower.com.storysflower.model.tables.tables.Occasion.OCCASION;

    /**
     * product table
     */
    public final Product PRODUCT = storysflower.com.storysflower.model.tables.tables.Product.PRODUCT;

    /**
     * product category table
     */
    public final ProductCategory PRODUCT_CATEGORY = storysflower.com.storysflower.model.tables.tables.ProductCategory.PRODUCT_CATEGORY;

    /**
     * rating table
     */
    public final Rating RATING = storysflower.com.storysflower.model.tables.tables.Rating.RATING;

    /**
     * recipient table
     */
    public final Recipient RECIPIENT = storysflower.com.storysflower.model.tables.tables.Recipient.RECIPIENT;

    /**
     * review table
     */
    public final Review REVIEW = storysflower.com.storysflower.model.tables.tables.Review.REVIEW;

    /**
     * topic table
     */
    public final Topic TOPIC = storysflower.com.storysflower.model.tables.tables.Topic.TOPIC;

    /**
     * user table
     */
    public final User USER = storysflower.com.storysflower.model.tables.tables.User.USER;

    /**
     * user role table
     */
    public final UserRole USER_ROLE = storysflower.com.storysflower.model.tables.tables.UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.BUY_PRODUCT_ID_SEQ,
            Sequences.CART_ID_SEQ,
            Sequences.CATEGORY_ID_SEQ,
            Sequences.CUSTOMER_ID_SEQ,
            Sequences.DEAL_PRODUCT_ID_SEQ,
            Sequences.FAVOURITE_ID_SEQ,
            Sequences.IMAGE_IMAGE_ID_SEQ,
            Sequences.OCCASION_OCCASION_ID_SEQ,
            Sequences.PRODUCT_ID_SEQ,
            Sequences.RATING_ID_SEQ,
            Sequences.RECIPIENT_ID_SEQ,
            Sequences.REVIEW_ID_SEQ,
            Sequences.TOPIC_TOPIC_ID_SEQ,
            Sequences.USER_ID_SEQ,
            Sequences.USER_ROLE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            BuyProduct.BUY_PRODUCT,
            Cart.CART,
            Category.CATEGORY,
            Customer.CUSTOMER,
            DealProduct.DEAL_PRODUCT,
            Favourite.FAVOURITE,
            Image.IMAGE,
            ImageProduct.IMAGE_PRODUCT,
            Occasion.OCCASION,
            Product.PRODUCT,
            ProductCategory.PRODUCT_CATEGORY,
            Rating.RATING,
            Recipient.RECIPIENT,
            Review.REVIEW,
            Topic.TOPIC,
            User.USER,
            UserRole.USER_ROLE);
    }
}
